### PR TITLE
Add support for multiple locale dir watch

### PR DESCRIPTION
**Pull request by felixmosh**

### CODE REVIEW

**Comment by felixmosh** [comment]
These are the changes that are needed to add support for multiple watch dirs :]

**Comment by felixmosh** [comment]
I guess that this is some limitation that comes from my code, I'll review a possible solution.

Side note, I didn't committed this change, but your code is registering a new hmr each time, it can be simplified.

```ts
import hoistNonReactStatics from 'hoist-non-react-statics';
import { useMemo } from 'react';
import { I18nSiteContextProvider } from '../contexts/I18nSiteContext';
import { createClient } from '../utils/i18nBrowserClient';
import { setupI18nextHmr } from '../utils/setupI18nextHmr';

let singeltonInstance=null;

setupI18nextHmr(() => singeltonInstance);

export const appWithSiteTranslations = (WrappedComponent) => {
  const AppWithSiteTranslations = (props) => {
    const serverData = props.pageProps?._i18nSite;

    const i18nInstance = useMemo(() => {
      if (!serverData) return null;

      const { initialSiteLocale, siteNamespaces, siteStore } = serverData;
      const client = createClient({
        lng: initialSiteLocale,
        ns: siteNamespaces,
        resources: siteStore,
        fallbackNS: siteNamespaces,
      });
      return client.i18n;
    }, [serverData]);

    if (i18nInstance) {
      singeltonInstance = i18nInstance
    }

    if (!serverData || !i18nInstance) {
      return <WrappedComponent {...props} />;
    }

    return (
      <I18nSiteContextProvider
        value={{ i18nSite: i18nInstance, supportedSiteLocales: serverData.supportedSiteLocales }}
      >
        <WrappedComponent {...props} />
      </I18nSiteContextProvider>
    );
  };

  return hoistNonReactStatics(AppWithSiteTranslations, WrappedComponent);
};
```

Anyway, maybe this getter function will be able to return an array of instances, and the HMR will do it stuff for each one of them... so it will look like:

```js
setupI18nextHmr(() => [singeltonInstance1, singeltonInstance2]);
```

**Comment by medihack** [comment]
Good hint with the singleton. And thanks for looking into this. I played around a bit with `client-hmr.js`, but unfortunately couldn't find a solution.

**Comment by felixmosh** [comment]
(Ops, I've wrote it on the wrong place 😅)

**Comment by medihack** [comment]
No prob, GitHub helps to keep the overview :-)

**Pull request merged**
